<<<<<<< HEAD
# Generated by Django 6.0.2 on 2026-02-20 12:32
=======
# Generated by Django 6.0.2 on 2026-02-20 19:32
>>>>>>> 30f0803 (Ultima versao w)

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('data_cadastro', models.DateField()),
            ],
=======
                ('nome', models.CharField(max_length=200, verbose_name='Nome Completo')),
                ('cpf', models.CharField(max_length=11, unique=True, verbose_name='CPF')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('telefone', models.CharField(max_length=15, verbose_name='Telefone')),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('esta_ativo', models.BooleanField(default=True, verbose_name='Está Ativo?')),
                ('data_cadastro', models.DateField(auto_now_add=True, verbose_name='Data de Cadastro')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nome'],
            },
>>>>>>> 30f0803 (Ultima versao w)
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('tipo', models.CharField(choices=[('ADM', 'Administrador'), ('REC', 'Recepcionista')], max_length=3)),
            ],
<<<<<<< HEAD
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
=======
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
                'ordering': ['nome'],
            },
>>>>>>> 30f0803 (Ultima versao w)
        ),
        migrations.CreateModel(
            name='Quarto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('numero', models.IntegerField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8)),
                ('tipo', models.CharField(max_length=10)),
                ('ocupado', models.BooleanField(default=False)),
            ],
=======
                ('numero', models.CharField(max_length=10, unique=True, verbose_name='Número do Quarto')),
                ('tipo', models.CharField(choices=[('simples', 'Simples'), ('luxo', 'Luxo'), ('suite_master', 'Suíte Master'), ('presidencial', 'Presidencial')], max_length=20, verbose_name='Tipo do Quarto')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição do Quarto')),
                ('preco_hora', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Preço por Hora')),
                ('preco_periodo', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Preço por Período')),
                ('preco_pernoite', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Preço por Pernoite')),
                ('capacidade', models.IntegerField(default=2, verbose_name='Capacidade de Pessoas')),
                ('status', models.CharField(choices=[('livre', 'Livre'), ('ocupado', 'Ocupado'), ('manutencao', 'Manutenção'), ('limpeza', 'Limpeza'), ('reservado', 'Reservado')], default='livre', max_length=20, verbose_name='Status do Quarto')),
                ('possui_garagem', models.BooleanField(default=False, verbose_name='Possui Garagem?')),
                ('possui_hidro', models.BooleanField(default=False, verbose_name='Possui Hidromassagem?')),
                ('possui_ar_condicionado', models.BooleanField(default=False, verbose_name='Possui Ar Condicionado?')),
                ('possui_frigobar', models.BooleanField(default=False, verbose_name='Possui Frigobar?')),
                ('possui_tv', models.BooleanField(default=False, verbose_name='Possui TV?')),
                ('possui_wifi', models.BooleanField(default=False, verbose_name='Possui Wi-Fi?')),
                ('esta_ativo', models.BooleanField(default=True, verbose_name='Está Ativo?')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Quarto',
                'verbose_name_plural': 'Quartos',
                'ordering': ['tipo', 'numero'],
            },
>>>>>>> 30f0803 (Ultima versao w)
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('data_entrada', models.DateTimeField()),
                ('data_saida', models.DateTimeField()),
                ('pago', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motel.cliente')),
                ('quarto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='motel.quarto')),
            ],
=======
                ('tipo_reserva', models.CharField(choices=[('hora', 'Hora'), ('periodo', 'Período'), ('pernoite', 'Pernoite')], max_length=20, verbose_name='Tipo de Reserva')),
                ('entrada', models.DateTimeField(auto_now_add=True, verbose_name='Data e Hora de Entrada')),
                ('saida', models.DateTimeField(verbose_name='Data e Hora de Saída')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada')], default='pendente', max_length=20, verbose_name='Status da Reserva')),
                ('status_pagamento', models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('cancelado', 'Cancelado')], default='pendente', max_length=20, verbose_name='Status do Pagamento')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor Total')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motel.cliente', verbose_name='Cliente')),
                ('quarto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='motel.quarto', verbose_name='Quarto')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['-entrada'],
            },
>>>>>>> 30f0803 (Ultima versao w)
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('tipo', models.CharField(choices=[('CC', 'Cartão de Crédito'), ('CD', 'Cartão de Débito'), ('DIN', 'Dinheiro à vista'), ('PIX', 'PIX')], max_length=20)),
=======
                ('tipo', models.CharField(choices=[('credito', 'Cartão de Crédito'), ('debito', 'Cartão de Débito'), ('dinheiro', 'Dinheiro à vista'), ('pix', 'PIX')], max_length=20)),
>>>>>>> 30f0803 (Ultima versao w)
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motel.reserva')),
            ],
        ),
    ]
