# Generated by Django 6.0.2 on 2026-02-20 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quarto',
            name='tipo',
            field=models.CharField(choices=[('BAS', 'BÁSICO'), ('VIP', 'PREMIUM')], max_length=10),
        ),
    ]
