# Generated by Django 6.0.2 on 2026-02-20 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motel', '0002_alter_quarto_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='motel.produto')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='motel.reserva')),
            ],
        ),
    ]
